### ISSUE TITLE
error in reago.py

### ISSUE THREAD

**Issue by leffj** [chengyuan/reago-1.1#10]
Hi, I'm getting the following error when running reago.py. Suggestions? This happens when I run this command:

`python reago.py test.fasta reago_assembled -l 151`

where test.fasta is:

> >1266.1 529 603 1 75
> CGTAGAGCTCATCGAGCGTTTCGGCGGAGCTCGATCCGGCGAGCAGTGCGACGGCGGCAAAGAGTGCCGACGATCTCCGTAAGATCGTCGGCAGAGATGCAGCGAACATTCCTTCCTCCCGAGACTTATCGTTCGGGGATTTTGCCGCCG
> >1266.2 529 599 1 71
> GCGTAGAGCTCATCGAGCGTTTCGGCGGAGCTCGATCCGGCGAGCAGTGCGACGGCGGCAAAGAGTGCCGACGATCTCCGTAAGATCGTCGGCAGAGATGCAGCGAACATTCCTTCCTCCCGAGACTTATCGTTCGGGGATTTTGCCGCCG"

This is the error message/traceback:

> Traceback (most recent call last):
>   File "reago.py", line 832, in <module>
>     subgraph = merge_bifurcation(subgraph)
>   File "reago.py", line 410, in merge_bifurcation
>     G = collapse_graph(G, list(collapse_candidate))
>   File "reago.py", line 310, in collapse_graph
>     G.remove_node(predecessor)
>   File ".../python2.7/site-packages/networkx/classes/digraph.py", line 461, in remove_node
>     raise NetworkXError("The node %s is not in the digraph."%(n,))
> networkx.exception.NetworkXError: The node 1266.1|1266.2 is not in the digraph.

**Comment by ViridianaAvila** [comment]
I have the same issue, any solutions you found?

**Comment by ViridianaAvila** [comment]
I have the same issues. Any solutions?
