### ISSUE TITLE
Error in Recovering 16S rRNAs

### ISSUE THREAD

**Issue by domenico-simone** [chengyuan/reago-1.1#11]
Hello, while running reago I got this error:

``` bash
$ reago_multit.py input_file.fasta input_file.out -l 125
Tue Oct  4 10:44:39 2016 REAGO (v1.10) started...
Input file: input_file.fasta
Parameters:
-e 0.05
-f 1350
-b 10
-l 125.0
-o 0.7
-t 30
Tue Oct  4 10:44:39 2016 Reading input file...
Tue Oct  4 10:45:28 2016 Initializing overlap graph...
Tue Oct  4 10:47:28 2016 Recovering 16S rRNAs...
Traceback (most recent call last):
  File "/home/domeni/glob/reago-1.1-master/reago.py", line 825, in <module>
    correct_sequencing_error(subgraph, 5)
  File "/home/domeni/glob/reago-1.1-master/reago.py", line 190, in correct_sequencing_error
    cur_base = orig_seq[i - alignment_to_starting_node[starting_node][read_id]]
IndexError: list index out of range
```

Thanks for your support
cheers

**Comment by slvrshot** [comment]
Were you able to figure this out @domenico-simone ? I got the same error.

**Comment by slvrshot** [comment]
Macbooks-MBP:Reago Jay$ python reago.py filter_out/filtered.fasta sample_out -l 101
Thu Feb 23 14:15:27 2017 REAGO (v1.10) started...
Input file: filter_out/filtered.fasta
Parameters:
-e 0.05
-f 1350
-b 10
-l 101.0
-o 0.7
-t 30
Thu Feb 23 14:15:27 2017 Reading input file...
Thu Feb 23 14:15:27 2017 Initializing overlap graph...
Thu Feb 23 14:15:27 2017 Recovering 16S rRNAs...
Traceback (most recent call last):
  File "reago.py", line 855, in <module>
    correct_sequencing_error(subgraph, 5)
  File "reago.py", line 220, in correct_sequencing_error
    cur_base = orig_seq[i - alignment_to_starting_node[starting_node][read_id]]
IndexError: list index out of range

**Comment by slvrshot** [comment]
All my input sequences are 150 bp.

**Comment by fredfarrell** [comment]
Hi, I had the same issue, thought I'd reply to this in case anyone else does! You just need to set the -l parameter to your sequence length (replace 101 in the command).
