### ISSUE TITLE
gt readjoiner prefilter: error

### ISSUE THREAD

**Issue by microbiaki** [chengyuan/reago-1.1#7]
Hello!

I am trying to run the example provide and I get the following error:

gt readjoiner prefilter: error: unknown option: -des (-help shows possible options)
gt readjoiner spmtest: error: fopen(): cannot open file 'sample_out/rj/graph.set.0.spm': No such file or directory
Traceback (most recent call last):
  File "reago.py", line 816, in <module>
    G = create_graph_using_rj(read_db, "graph")
  File "reago.py", line 110, in create_graph_using_rj
    f = open(output_dir + "/rj/" + graph_fn + ".set.des")
IOError: [Errno 2] No such file or directory: 'sample_out//rj/graph.set.des'

I have Ubuntu 14.04 and I installed genome tools through sudo apt-get install genometools

Did this cause the issue? Any ideas on how to fix it?

Thank you,
Maria

**Comment by debjitde01** [comment]
I also have the same issue.. please help to solve this problem
